### PR TITLE
Clarify the assignable parameters are objects

### PR DESCRIPTION
**Pull request by denis-sokolov**

### CODE REVIEW

**Comment by louy** [comment]
So the problem with this approach is that it will break in TS 2.0 with [non-nullable types](https://github.com/Microsoft/TypeScript/pull/7140), because `null` does not extend `Object`. 

`assign({}, null)` is totally fine in javascript. it should be fine in typescript. However, `assign(null, {})` will throw an error, which is why I only added `extends Object` to the first type argument.

I don't see what's the advantage of making this change, so if you can show it to me I would happily merge this PR.

**Comment by denis-sokolov** [comment]
The intention was to prevent mistakes where strings, numbers, or booleans are passed in (`Object.assign({}, 'foo')`). But feel free to close if you think it’s not worth the problems.
The news of null-aware types being accepted to TypeScript are useful to me, thank you for sharing.

**Comment by louy** [comment]
I see your point. The problem is, [it doesn't work](http://www.typescriptlang.org/play/#src=function%20assign%3CA%20extends%20Object%3E%28a%3A%20A%29%3A%20A%3B%0Afunction%20assign%3CA%20extends%20Object%2C%20B%20extends%20Object%3E%28a%3A%20A%2C%20b%3A%20B%29%3A%20A%20%26%20B%3B%0Afunction%20assign%3CA%20extends%20Object%2C%20B%20extends%20Object%2C%20C%20extends%20Object%3E%28a%3A%20A%2C%20b%3A%20B%2C%20c%3A%20C%29%3A%20A%20%26%20B%20%26%20C%3B%0Afunction%20assign%3CA%20extends%20Object%2C%20B%20extends%20Object%2C%20C%20extends%20Object%2C%20D%20extends%20Object%3E%28a%3A%20A%2C%20b%3A%20B%2C%20c%3A%20C%2C%20d%3A%20D%29%3A%20A%20%26%20B%20%26%20C%20%26%20D%3B%0Afunction%20assign%3CA%20extends%20Object%2C%20B%20extends%20Object%2C%20C%20extends%20Object%2C%20D%20extends%20Object%2C%20E%20extends%20Object%3E%28a%3A%20A%2C%20b%3A%20B%2C%20c%3A%20C%2C%20d%3A%20D%2C%20e%3A%20E%29%3A%20A%20%26%20B%20%26%20C%20%26%20D%20%26%20E%3B%0Afunction%20assign%3CA%20extends%20Object%3E%28...a%3A%20A%5B%5D%29%3A%20A%20%7B%20throw%20new%20Error%3B%20%7D%0A%0Aassign%28%7B%7D%2C%201%2C%20's'%29%3B%0A) like that. `Number`, `String` and all types but `void` are `Object`s.

``` ts
function assign<A extends Object>(a: A): A;
function assign<A extends Object, B extends Object>(a: A, b: B): A & B;
function assign<A extends Object, B extends Object, C extends Object>(a: A, b: B, c: C): A & B & C;
function assign<A extends Object, B extends Object, C extends Object, D extends Object>(a: A, b: B, c: C, d: D): A & B & C & D;
function assign<A extends Object, B extends Object, C extends Object, D extends Object, E extends Object>(a: A, b: B, c: C, d: D, e: E): A & B & C & D & E;
function assign<A extends Object>(...a: A[]): A { throw new Error('Not implemented'); }

assign({}, 1, 's', null); // No errors!
```

**Comment by louy** [comment]
If you actually look at [lib.core.d.ts](https://github.com/Microsoft/TypeScript/blob/master/lib/lib.core.d.ts#L277) in typescript core, you can see that `String` is just an interface. There's no way to exclude it unfortunately. (I wish there was a way)

**Comment by denis-sokolov** [comment]
Ha, ha, ha, I never knew that about TypeScript. Thank you and sorry for wasting your time!

**Comment by louy** [comment]
Don't worry about it :)

**Pull request closed without merging**
